ALTER TABLE users ALTER COLUMN disabled DROP DEFAULT;
ALTER TABLE users ALTER disabled TYPE bool USING CASE WHEN disabled=0 THEN FALSE ELSE TRUE END;
ALTER TABLE users ALTER COLUMN disabled SET DEFAULT FALSE;

ALTER TABLE users ADD COLUMN default_owner_org_id bigint DEFAULT 10100021;
ALTER TABLE menu ADD COLUMN PATH varchar;
ALTER TABLE menu ADD COLUMN deleted_by bigint;
ALTER TABLE menu ADD COLUMN created_date bigint;

ALTER TABLE menu ALTER COLUMN disabled DROP DEFAULT;
ALTER TABLE menu ALTER disabled TYPE bool USING CASE WHEN disabled=0 THEN FALSE ELSE TRUE END;

ALTER TABLE menu ALTER COLUMN disabled SET DEFAULT FALSE;